module ysyxSoCASIC_top (
  input         clock,
                reset,
                clock_half,
                oldIPClock,
                oldIPReset,
  output        qspi_sck_o,
  output [3:0]  qspi_nss_o,
                qspi_en_o,
                qspi_out_o,
  input  [3:0]  qspi_in_i,
  output        psram_sck,
  output [1:0]  psram_nss,
  output [3:0]  psram_en_o,
  input  [3:0]  psram_in_i,
  output [3:0]  psram_out_o,
  input         intr_from_chipSlave,
                uart0_rx,
  output        uart0_tx,
  input         uart1_uart_rx_i,
  output        uart1_uart_tx_o,
                spi_sck,
  output [7:0]  spi_ss,
  output        spi_mosi,
  input         spi_miso,
                ps2_ps2_clk_i,
                ps2_ps2_dat_i,
  input  [31:0] gpio0_gpio_in_i,
  output [31:0] gpio0_gpio_out_o,
                gpio0_gpio_dir_o,
                gpio0_gpio_alt_in_o,
  input  [31:0] gpio0_gpio_alt_0_out_i,
                gpio0_gpio_alt_0_dir_i,
                gpio0_gpio_alt_1_out_i,
                gpio0_gpio_alt_1_dir_i,
                gpio1_i_gpio_in_i,
  output [31:0] gpio1_i_gpio_out_o,
                gpio1_i_gpio_dir_o,
                gpio1_i_gpio_alt_in_o,
  input  [31:0] gpio1_i_gpio_alt_0_out_i,
                gpio1_i_gpio_alt_0_dir_i,
                gpio1_i_gpio_alt_1_out_i,
                gpio1_i_gpio_alt_1_dir_i,
                gpio2_i_gpio_in_i,
  output [31:0] gpio2_i_gpio_out_o,
                gpio2_i_gpio_dir_o,
                gpio2_i_gpio_alt_in_o,
  input  [31:0] gpio2_i_gpio_alt_0_out_i,
                gpio2_i_gpio_alt_0_dir_i,
                gpio2_i_gpio_alt_1_out_i,
                gpio2_i_gpio_alt_1_dir_i,
  output [3:0]  pwm0_pwm_o,
                pwm1_pwm_o,
  input         i2c_scl_i,
  output        i2c_scl_o,
                i2c_scl_dir_o,
  input         i2c_sda_i,
  output        i2c_sda_o,
                i2c_sda_dir_o,
                i2s_mclk_o,
                i2s_sck_o,
  input         i2s_sck_i,
  output        i2s_sck_en_o,
                i2s_ws_o,
  input         i2s_ws_i,
  output        i2s_ws_en_o,
                i2s_sd_o,
  input         i2s_sd_i,
                timer0_exclk_i,
                timer0_capch_i,
                timer1_exclk_i,
                timer1_capch_i,
                timer2_exclk_i,
                timer2_capch_i,
                timer3_exclk_i,
                timer3_capch_i,
                rcu_ext_lfosc_clk_i,
                rcu_ext_hfosc_clk_i,
                rcu_ext_audosc_clk_i,
                rcu_ext_rst_n_i,
                rcu_wdt_rst_n_i,
                rcu_pll_en_i,
  input  [2:0]  rcu_clk_cfg_i,
  input  [4:0]  rcu_core_sel_i,
  output [4:0]  rcu_core_sel_o,
  output [6:0]  rcu_clk_o,
                rcu_rst_n_o,
  input  [1:0]  core_sel,
  input         core_irq
);


  ysyxSoCASIC asic (
    .clock                    (clock),
    .reset                    (reset),
    .clock_half               (divReg),
    .oldIPClock               (clock),
    .oldIPReset               (reset),
    .qspi_sck_o               (qspi_sck_o),
    .qspi_nss_o               (qspi_nss_o),
    .qspi_en_o                (qspi_en_o),
    .qspi_out_o               (qspi_out_o),
    .qspi_in_i                (qspi_in_i),

    .psram_sck                (psram_sck),
    .psram_nss                (psram_nss),
    .psram_en_o               (psram_en_o),
    .psram_in_i               (psram_in_i),
    .psram_out_o              (psram_out_o),

    .intr_from_chipSlave      (intr_from_chipSlave),
    .uart0_rx                 (uart0_rx),
    .uart0_tx                 (uart0_tx),
    .uart1_uart_rx_i          (uart1_uart_rx_i),
    .uart1_uart_tx_o          (uart1_uart_tx_o),
    .spi_sck                  (spi_sck),
    .spi_ss                   (spi_ss),
    .spi_mosi                 (spi_mosi),
    .spi_miso                 (spi_miso),

    .ps2_ps2_clk_i            (ps2_ps2_clk_i),
    .ps2_ps2_dat_i            (ps2_ps2_dat_i),
    .gpio0_gpio_in_i          (gpio0_gpio_in_i),
    .gpio0_gpio_out_o         (gpio0_gpio_out_o),
    .gpio0_gpio_dir_o         (gpio0_gpio_dir_o),
    .gpio0_gpio_alt_in_o      (gpio0_gpio_alt_in_o),
    .gpio0_gpio_alt_0_out_i   (gpio0_gpio_alt_0_out_i),
    .gpio0_gpio_alt_0_dir_i   (gpio0_gpio_alt_0_dir_i),
    .gpio0_gpio_alt_1_out_i   (gpio0_gpio_alt_1_out_i),
    .gpio0_gpio_alt_1_dir_i   (gpio0_gpio_alt_1_dir_i),
    .gpio1_i_gpio_in_i        (gpio1_i_gpio_in_i),
    .gpio1_i_gpio_out_o       (gpio1_i_gpio_out_o),
    .gpio1_i_gpio_dir_o       (gpio1_i_gpio_dir_o),
    .gpio1_i_gpio_alt_in_o    (gpio1_i_gpio_alt_in_o),
    .gpio1_i_gpio_alt_0_out_i (gpio1_i_gpio_alt_0_out_i),
    .gpio1_i_gpio_alt_0_dir_i (gpio1_i_gpio_alt_0_dir_i),
    .gpio1_i_gpio_alt_1_out_i (gpio1_i_gpio_alt_1_out_i),
    .gpio1_i_gpio_alt_1_dir_i (gpio1_i_gpio_alt_1_dir_i),
    .gpio2_i_gpio_in_i        (gpio2_i_gpio_in_i),
    .gpio2_i_gpio_out_o       (gpio2_i_gpio_out_o),
    .gpio2_i_gpio_dir_o       (gpio2_i_gpio_dir_o),
    .gpio2_i_gpio_alt_in_o    (gpio2_i_gpio_alt_in_o),
    .gpio2_i_gpio_alt_0_out_i (gpio2_i_gpio_alt_0_out_i),
    .gpio2_i_gpio_alt_0_dir_i (gpio2_i_gpio_alt_0_dir_i),
    .gpio2_i_gpio_alt_1_out_i (gpio2_i_gpio_alt_1_out_i),
    .gpio2_i_gpio_alt_1_dir_i (gpio2_i_gpio_alt_1_dir_i),
    .pwm0_pwm_o               (pwm0_pwm_o),
    .pwm1_pwm_o               (pwm1_pwm_o),
    .i2c_scl_i                (i2c_scl_i),
    .i2c_scl_o                (i2c_scl_o),
    .i2c_scl_dir_o            (i2c_scl_dir_o),
    .i2c_sda_i                (i2c_sda_i),
    .i2c_sda_o                (i2c_sda_o),
    .i2c_sda_dir_o            (i2c_sda_dir_o),
    .i2s_mclk_o               (i2s_mclk_o),
    .i2s_sck_o                (i2s_sck_o),
    .i2s_sck_i                (i2s_sck_i),
    .i2s_sck_en_o             (i2s_sck_en_o),
    .i2s_ws_o                 (i2s_ws_o),
    .i2s_ws_i                 (i2s_ws_i),
    .i2s_ws_en_o              (i2s_ws_en_o),
    .i2s_sd_o                 (i2s_sd_o),
    .i2s_sd_i                 (i2s_sd_i),
    .timer0_exclk_i           (timer0_exclk_i),
    .timer0_capch_i           (timer0_capch_i),
    .timer1_exclk_i           (timer1_exclk_i),
    .timer1_capch_i           (timer1_capch_i),
    .timer2_exclk_i           (timer2_exclk_i),
    .timer2_capch_i           (timer2_capch_i),
    .timer3_exclk_i           (timer3_exclk_i),
    .timer3_capch_i           (timer3_capch_i),
    .rcu_ext_lfosc_clk_i      (rcu_ext_lfosc_clk_i),
    .rcu_ext_hfosc_clk_i      (rcu_ext_hfosc_clk_i),
    .rcu_ext_audosc_clk_i     (rcu_ext_audosc_clk_i),
    .rcu_ext_rst_n_i          (rcu_ext_rst_n_i),
    .rcu_wdt_rst_n_i          (rcu_wdt_rst_n_i),
    .rcu_pll_en_i             (rcu_pll_en_i),
    .rcu_clk_cfg_i            (rcu_clk_cfg_i),
    .rcu_core_sel_i           (rcu_core_sel_i),
    .rcu_core_sel_o           (rcu_core_sel_o),
    .rcu_clk_o                (rcu_clk_o),
    .rcu_rst_n_o              (rcu_rst_n_o),
    .core_sel                 (core_sel),
    .core_irq                 (core_irq)
  );


endmodule

