module core_wrapper(
  input  wire          io_master_awready,
  output wire          io_master_awvalid,
  output wire [31:0]   io_master_awaddr,
  output wire [3:0]    io_master_awid,
  output wire [7:0]    io_master_awlen,
  output wire [2:0]    io_master_awsize,
  output wire [1:0]    io_master_awburst,
  input  wire          io_master_wready,
  output wire          io_master_wvalid,
  output wire [31:0]   io_master_wdata,
  output wire [3:0]    io_master_wstrb,
  output wire          io_master_wlast,
  output wire          io_master_bready,
  input  wire          io_master_bvalid,
  input  wire [1:0]    io_master_bresp,
  input  wire [3:0]    io_master_bid,
  input  wire          io_master_arready,
  output wire          io_master_arvalid,
  output wire [31:0]   io_master_araddr,
  output wire [3:0]    io_master_arid,
  output wire [7:0]    io_master_arlen,
  output wire [2:0]    io_master_arsize,
  output wire [1:0]    io_master_arburst,
  output wire          io_master_rready,
  input  wire          io_master_rvalid,
  input  wire [1:0]    io_master_rresp,
  input  wire [31:0]   io_master_rdata,
  input  wire          io_master_rlast,
  input  wire [3:0]    io_master_rid,
  output wire          io_slave_awready,
  input  wire          io_slave_awvalid,
  input  wire [31:0]   io_slave_awaddr,
  input  wire [3:0]    io_slave_awid,
  input  wire [7:0]    io_slave_awlen,
  input  wire [2:0]    io_slave_awsize,
  input  wire [1:0]    io_slave_awburst,
  output wire          io_slave_wready,
  input  wire          io_slave_wvalid,
  input  wire [31:0]   io_slave_wdata,
  input  wire [3:0]    io_slave_wstrb,
  input  wire          io_slave_wlast,
  input  wire          io_slave_bready,
  output wire          io_slave_bvalid,
  output wire [1:0]    io_slave_bresp,
  output wire [3:0]    io_slave_bid,
  output wire          io_slave_arready,
  input  wire          io_slave_arvalid,
  input  wire [31:0]   io_slave_araddr,
  input  wire [3:0]    io_slave_arid,
  input  wire [7:0]    io_slave_arlen,
  input  wire [2:0]    io_slave_arsize,
  input  wire [1:0]    io_slave_arburst,
  input  wire          io_slave_rready,
  output wire          io_slave_rvalid,
  output wire [1:0]    io_slave_rresp,
  output wire [31:0]   io_slave_rdata,
  output wire          io_slave_rlast,
  output wire [3:0]    io_slave_rid,
  input  wire          io_interrupt,
  input  wire          clock,
  input  wire          reset,
  input  wire [1:0]    core_sel
);

ysyx_26010010 u_cpu(
.io_master_awready(io_master_awready),
.io_master_awvalid(io_master_awvalid),
.io_master_awaddr(io_master_awaddr),
.io_master_awid(io_master_awid),
.io_master_awlen(io_master_awlen),
.io_master_awsize(io_master_awsize),
.io_master_awburst(io_master_awburst),
.io_master_wready(io_master_wready),
.io_master_wvalid(io_master_wvalid),
.io_master_wdata(io_master_wvalid),
.io_master_wstrb(io_master_wstrb),
.io_master_wlast(io_master_wlast),
.io_master_bready(io_master_bready),
.io_master_bvalid(io_master_bvalid),
.io_master_bresp(io_master_bresp),
.io_master_bid(io_master_bid),
.io_master_arready(io_master_arready),
.io_master_arvalid(io_master_arvalid),
.io_master_araddr(io_master_araddr),
.io_master_arid(io_master_arid),
.io_master_arlen(io_master_arlen),
.io_master_arsize(io_master_arsize),
.io_master_arburst(io_master_arburst),
.io_master_rready(io_master_rready),
.io_master_rvalid(io_master_rvalid),
.io_master_rresp(io_master_rresp),
.io_master_rdata(io_master_rdata),
.io_master_rlast(io_master_rlast),
.io_master_rid(io_master_rid),
.io_slave_awready(io_slave_awready),
.io_slave_awvalid(io_slave_awvalid),
.io_slave_awaddr(io_slave_awaddr),
.io_slave_awid(io_slave_awid),
.io_slave_awlen(io_slave_awlen),
.io_slave_awsize(io_slave_awsize),
.io_slave_awburst(io_slave_awburst),
.io_slave_wready(io_slave_wready),
.io_slave_wvalid(io_slave_wvalid),
.io_slave_wdata(io_slave_wdata),
.io_slave_wstrb(io_slave_wstrb),
.io_slave_wlast(io_slave_wlast),
.io_slave_bready(io_slave_bready),
.io_slave_bvalid(io_slave_bvalid),
.io_slave_bresp(io_slave_bresp),
.io_slave_bid(io_slave_bid),
.io_slave_arready(io_slave_arready),
.io_slave_arvalid(io_slave_arvalid),
.io_slave_araddr(io_slave_araddr),
.io_slave_arid(io_slave_arid),
.io_slave_arlen(io_slave_arlen),
.io_slave_arsize(io_slave_arsize),
.io_slave_arburst(io_slave_arburst),
.io_slave_rready(io_slave_rready),
.io_slave_rvalid(io_slave_rvalid),
.io_slave_rresp(io_slave_rresp),
.io_slave_rdata(io_slave_rdata),
.io_slave_rlast(io_slave_rlast),
.io_slave_rid(io_slave_rid),
.io_interrupt(io_interrupt),
.clock(clock),
.reset(reset)

);

endmodule
